const state=JSON.parse(localStorage.getItem('ssdb')||'null')||{visitors:[{id:'VIS001',name:'Thabo Nkosi',type:'Parent',host:'Lerato Nkosi',purpose:'Meeting',status:'Inside',date:new Date().toISOString().slice(0,10),checkin:'07:42'},{id:'VIS002',name:'Sarah Bennett',type:'Guardian',host:'Mia Bennett',purpose:'Collection',status:'Checked Out',date:new Date().toISOString().slice(0,10),checkin:'08:10',checkout:'09:05'}],incidents:[{id:'INC001',category:'Access Control',priority:'High',location:'Main Gate',status:'Open',date:new Date().toISOString().slice(0,10),reported:'S. Dlamini'}],learners:[{id:'L001',name:'Lerato Nkosi',grade:'4',class:'4B'}],staff:[{id:'S001',name:'Ms Molefe',role:'Teacher'}],notifications:[{title:'Visitor access requires attention',status:'Unread'}],audit:[]};
function save(){localStorage.setItem('ssdb',JSON.stringify(state))}function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
const pages=['Dashboard','Leadership','Visitors','Incidents','Notifications','Learners','Parents','Staff','Security Officers','Reports','Audit Trail','Settings'];
function shell(page,html){document.getElementById('app').innerHTML=`<div class='layout'><aside class='side'><div class='brand'>🛡 SchoolShield<span>Greenfield Primary School</span></div><div class='nav'>${pages.map(x=>`<button class='${x==page?'active':''}' onclick="render('${x}')">${x}</button>`).join('')}</div></aside><main class='main'><header class='top'><div><b>${page}</b></div><div>🔔 &nbsp; ⚙️ &nbsp; <b>Ms. N. Mokoena</b></div></header><section class='content'>${html}</section></main></div>`}
function dashboard(){let inside=state.visitors.filter(v=>v.status==='Inside').length,out=state.visitors.filter(v=>v.status==='Checked Out').length;shell('Dashboard',`<div class='row'><div><h1>Good day, Ms. Mokoena</h1><p class='muted'>Here's what's happening on campus today.</p></div></div><div class='stats'>${[['Visitors Today',state.visitors.length],['Currently on Campus',inside],['Checked Out',out],['Total Learners',state.learners.length],['Total Staff',state.staff.length],['Security Officers',2]].map(x=>`<div class='card'><div class='muted'>${x[0]}</div><div class='num'>${x[1]}</div></div>`).join('')}</div><h2>Quick Actions</h2><div class='actions'><button class='action' onclick="render('Visitors')">➕ Register Visitor</button><button class='action' onclick="qr()">▣ Scan QR Code</button><button class='action' onclick="render('Incidents')">⚠ Report Incident</button><button class='action' onclick="emergency()">🚨 Emergency Alert</button><button class='action' onclick="render('Staff')">👥 Manage Staff</button><button class='action' onclick="render('Learners')">🎓 Register Learner</button><button class='action' onclick="render('Reports')">📊 View Reports</button></div><div class='card' style='margin-top:20px'><h2>Live Visitor Monitoring</h2>${visitorTable()}</div>`)}
function visitorTable(){return `<table><tr><th>ID</th><th>Visitor</th><th>Host</th><th>Status</th><th>Action</th></tr>${state.visitors.map(v=>`<tr><td>${v.id}</td><td>${v.name}</td><td>${v.host}</td><td><span class='badge ${v.status==='Inside'?'inside':'out'}'>${v.status}</span></td><td>${v.status==='Inside'?`<button class='btn gray' onclick="checkout('${v.id}')">Check out</button>`:'—'}</td></tr>`).join('')}</table>`}
function visitors(){shell('Visitors',`<div class='row'><div><h1>Visitor History</h1><p class='muted'>Manage and monitor campus visitors.</p></div><button class='btn' onclick='visitorForm()'>Register Visitor</button></div><div class='card'>${visitorTable()}</div>`)}
function visitorForm(){shell('Visitors',`<div class='row'><h1>Register Visitor</h1><button class='btn gray' onclick="render('Visitors')">Back</button></div><div class='card form'><form onsubmit='addVisitor(event)'><div class='grid'><div class='field'><label>Full Name</label><input name='name' required></div><div class='field'><label>Visitor ID</label><input name='id' required></div><div class='field'><label>Visitor Type</label><select name='type'><option>Parent</option><option>Guardian</option><option>Supplier</option></select></div><div class='field'><label>Person Being Visited</label><input name='host' required></div><div class='field full'><label>Purpose</label><input name='purpose' required></div></div><br><button class='btn'>Register Visitor</button></form></div>`)}
function addVisitor(e){e.preventDefault();let f=new FormData(e.target);state.visitors.unshift({id:f.get('id'),name:f.get('name'),type:f.get('type'),host:f.get('host'),purpose:f.get('purpose'),status:'Inside',date:new Date().toISOString().slice(0,10),checkin:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});state.audit.unshift({action:'Visitor registered',time:new Date().toLocaleString()});save();toast('Visitor registered successfully');render('Visitors')}
function checkout(id){let v=state.visitors.find(x=>x.id==id);v.status='Checked Out';v.checkout=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});state.audit.unshift({action:'Visitor checked out',time:new Date().toLocaleString()});save();toast('Visitor checked out');render('Visitors')}
function incidents(){shell('Incidents',`<div class='row'><div><h1>Incident Management</h1><p class='muted'>Track school safety incidents.</p></div><button class='btn' onclick='incidentForm()'>Report Incident</button></div><div class='card'><table><tr><th>ID</th><th>Category</th><th>Priority</th><th>Location</th><th>Status</th></tr>${state.incidents.map(i=>`<tr><td>${i.id}</td><td>${i.category}</td><td>${i.priority}</td><td>${i.location}</td><td><span class='badge open'>${i.status}</span></td></tr>`).join('')}</table></div>`)}
function incidentForm(){shell('Incidents',`<h1>Report Incident</h1><div class='card form'><form onsubmit='addIncident(event)'><div class='grid'><div class='field'><label>Category</label><input name='category' required></div><div class='field'><label>Priority</label><select name='priority'><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><div class='field'><label>Location</label><input name='location' required></div><div class='field'><label>Reported By</label><input name='reported' value='Ms. N. Mokoena'></div><div class='field full'><label>Description</label><textarea name='description' required></textarea></div></div><br><button class='btn'>Submit Incident</button></form></div>`)}
function addIncident(e){e.preventDefault();let f=new FormData(e.target);state.incidents.unshift({id:'INC'+Date.now().toString().slice(-4),category:f.get('category'),priority:f.get('priority'),location:f.get('location'),reported:f.get('reported'),status:'Open',date:new Date().toISOString().slice(0,10)});state.notifications.unshift({title:'New incident reported',status:'Unread'});state.audit.unshift({action:'Incident created',time:new Date().toLocaleString()});save();toast('Incident reported');render('Incidents')}
function learners(){shell('Learners',`<div class='row'><h1>Learners</h1><button class='btn' onclick='learnerForm()'>Register Learner</button></div><div class='card'><table><tr><th>ID</th><th>Name</th><th>Grade</th><th>Class</th></tr>${state.learners.map(l=>`<tr><td>${l.id}</td><td>${l.name}</td><td>${l.grade}</td><td>${l.class}</td></tr>`).join('')}</table></div>`)}
function learnerForm(){shell('Learners',`<h1>Register Learner</h1><div class='card form'><form onsubmit='addLearner(event)'><div class='grid'><div class='field'><label>Name</label><input name='name' required></div><div class='field'><label>ID</label><input name='id' required></div><div class='field'><label>Grade</label><input name='grade'></div><div class='field'><label>Class</label><input name='class'></div></div><br><button class='btn'>Save Learner</button></form></div>`)}
function addLearner(e){e.preventDefault();let f=new FormData(e.target);state.learners.push({id:f.get('id'),name:f.get('name'),grade:f.get('grade'),class:f.get('class')});save();toast('Learner registered');render('Learners')}
function staff(){shell('Staff',`<div class='row'><h1>Staff</h1><button class='btn' onclick='staffForm()'>Add Staff</button></div><div class='card'><table><tr><th>ID</th><th>Name</th><th>Role</th></tr>${state.staff.map(s=>`<tr><td>${s.id}</td><td>${s.name}</td><td>${s.role}</td></tr>`).join('')}</table></div>`)}
function staffForm(){shell('Staff',`<h1>Add Staff Member</h1><div class='card form'><form onsubmit='addStaff(event)'><div class='grid'><div class='field'><label>Name</label><input name='name' required></div><div class='field'><label>ID</label><input name='id' required></div><div class='field full'><label>Role</label><input name='role' required></div></div><br><button class='btn'>Add Staff</button></form></div>`)}
function addStaff(e){e.preventDefault();let f=new FormData(e.target);state.staff.push({id:f.get('id'),name:f.get('name'),role:f.get('role')});save();toast('Staff member added');render('Staff')}
function leadership(){shell('Leadership',`<h1>Leadership Dashboard</h1><div class='stats'>${[['Visitors',state.visitors.length],['Inside',state.visitors.filter(v=>v.status==='Inside').length],['Incidents',state.incidents.length],['Open',state.incidents.filter(i=>i.status==='Open').length],['Alerts',state.notifications.length],['Security',2]].map(x=>`<div class='card'><div class='muted'>${x[0]}</div><div class='num'>${x[1]}</div></div>`).join('')}</div><div class='card' style='margin-top:20px'><h2>Live Visitor Monitoring</h2>${visitorTable()}</div>`)}
function notifications(){shell('Notifications',`<div class='row'><h1>Notifications</h1><button class='btn gray' onclick='markRead()'>Mark all read</button></div><div class='card'>${state.notifications.map(n=>`<div style='padding:15px;border-bottom:1px solid #e5e7eb'><b>${n.title}</b><div class='muted'>${n.status}</div></div>`).join('')}</div>`)}function markRead(){state.notifications.forEach(n=>n.status='Read');save();toast('Notifications updated');render('Notifications')}
function qr(){shell('Visitors',`<h1>QR Scanner</h1><div class='card' style='max-width:600px;text-align:center'><div style='height:260px;border:3px dashed #2563eb;border-radius:14px;display:grid;place-items:center;font-size:70px'>▣</div><br><button class='btn' onclick="toast('QR Scan successful: Thabo Nkosi')">Simulate Scan</button></div>`)}
function emergency(){document.body.insertAdjacentHTML('beforeend',`<div class='modalbg' id='m'><div class='modal'><h2>Emergency Alert</h2><p>This will create a high priority emergency notification.</p><input id='loc' placeholder='Location' value='Main Gate' style='width:100%;padding:10px;margin:8px 0'><textarea id='msg' style='width:100%;height:90px'>Emergency assistance required.</textarea><br><br><button class='btn gray' onclick="document.getElementById('m').remove()">Cancel</button> <button class='btn red' onclick='sendEmergency()'>Send Alert</button></div></div>`)}function sendEmergency(){state.notifications.unshift({title:'EMERGENCY ALERT',status:'Unread'});state.audit.unshift({action:'Emergency alert sent',time:new Date().toLocaleString()});save();document.getElementById('m').remove();toast('Emergency alert sent')}
function reports(){shell('Reports',`<h1>Reports</h1><div class='stats'><div class='card'><div class='muted'>Visitors</div><div class='num'>${state.visitors.length}</div></div><div class='card'><div class='muted'>Incidents</div><div class='num'>${state.incidents.length}</div></div><div class='card'><div class='muted'>Learners</div><div class='num'>${state.learners.length}</div></div></div><div class='card' style='margin-top:20px'><h2>Monthly Activity</h2><div style='display:flex;align-items:end;height:180px;gap:12px'>${[45,70,55,90,65,100,75,85].map(x=>`<div style='flex:1;background:#2563eb;height:${x}%;border-radius:6px'></div>`).join('')}</div></div>`)}
function audit(){shell('Audit Trail',`<h1>Audit Trail</h1><div class='card'><table><tr><th>Action</th><th>Time</th></tr>${state.audit.map(a=>`<tr><td>${a.action}</td><td>${a.time}</td></tr>`).join('')}</table></div>`)}
function simple(name){shell(name,`<h1>${name}</h1><div class='card'><p>This prototype module is ready for demonstration.</p><p class='muted'>Navigation and the SchoolShield design system are implemented.</p></div>`)}
function render(p){({Dashboard:dashboard,Leadership:leadership,Visitors:visitors,Incidents:incidents,Notifications:notifications,Learners:learners,Parents:()=>simple('Parents'),Staff:staff,'Security Officers':()=>simple('Security Officers'),Reports:reports,'Audit Trail':audit,Settings:()=>simple('Settings')}[p]||dashboard)()}render('Dashboard');
